default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: <%= ENV['WISHDREAM_DATABASE_PASSWORD'] %>
  host: db

development:
  <<: *default
  database: wishdream_development

test:
  <<: *default
  database: wishdream_test

production:
  <<: *default
  database: wishdream_production
  username: wishdream
  password: <%= ENV['WISHDREAM_DATABASE_PASSWORD'] %>
